#!/bin/bash
# SAVE AS: install_apps.sh

# --- CONFIG ---
HYPR_CONFIG="$HOME/.config/hypr/hyprland.conf"
# --------------

echo "=== PHASE 2: APPS & LOOKS ==="

# 1. Install Daily Apps
echo "Installing Apps..."
yay -S --needed --noconfirm discord vlc steam flatpak nwg-displays \
    ttf-jetbrains-mono-nerd ttf-material-design-icons qt6-declarative qt6-svg

# 2. Setup Flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# 3. Set Defaults (VLC)
xdg-mime default vlc.desktop audio/mpeg
xdg-mime default vlc.desktop audio/mp4

# 4. INSTALL END-4 DOTFILES (The Main Event)
echo "Launching End-4 Installer..."
echo "IMPORTANT: Say YES to installing dependencies/packages when asked."
bash <(curl -s https://ii.clsty.link/get)

# 5. APPLY MONITOR FIXES (Run this AFTER the End-4 script finishes)
echo "Applying Monitor & Scaling Config..."

# We append your specific dual-monitor setup to the NEW config generated by End-4
cat <<EOT >> "$HYPR_CONFIG"

# --- USER HARDWARE CONFIG ---
# Monitor 1: 1080p @ 144Hz (Main Display - Port 1)
monitor = DP-1, 1920x1080@144, 0x0, 1

# Monitor 2: 4K @ 60Hz (Second Display - Port 2) - Scaled 1.5x
# Note: Since it is DP, it is likely DP-2. 
# If it doesn't light up, run 'hyprctl monitors' to check if it's DP-3.
monitor = DP-2, 3840x2160@60, 1920x0, 1.5

# Fix Blurry Apps on Scaled Monitor
xwayland {
  force_zero_scaling = true
}

# Fix Qt/Electron Scaling
env = GDK_SCALE,2
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
EOT

# Steam Font Fix
echo "Xft.dpi: 144" > "$HOME/.Xresources"
echo "xrdb -merge ~/.Xresources" >> "$HYPR_CONFIG"

echo "=== DONE! ==="
echo "Press SUPER+M (or the logout button) to reload Hyprland."
